language: android
dist: trusty
before_install:
  - yes | sdkmanager "build-tools;28.0.3"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
script:
- "./gradlew cleanBuildCache clean assembleDebug --stacktrace"
before_deploy:
- openssl aes-256-cbc -K $encrypted_f89c32a926bf_key -iv $encrypted_f89c32a926bf_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google-services.json app/google-services.json
deploy:
  skip_cleanup: true
  provider: script
  script:
  - "./gradlew publishRelease"
  on:
    branch: master